In [1]:
import pandas as pd
import numpy as np

In [52]:
date = pd.read_csv('../../EDA/data/orders.csv')
time = pd.read_csv('../../EDA/data/messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [ ]:
#date is in object format, we need to convert it to datetime format
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [ ]:
#converting date column to datetime format using pandas to_datetime function
date['date'] = pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [ ]:
#Year
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
805 2019-11-28        6339       26       7       2019
364 2019-03-26        5687       13      11       2019
636 2018-11-01        1744       13       4       2018
555 2019-08-15        3422       13       2       2019
238 2018-08-24         496       26       1       2018

In [ ]:
#Month and day

date['date_month'] = date['date'].dt.month
date['date_day'] = date['date'].dt.day
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month  date_day
279 2019-12-05        2884        2      19       2019          12         5
687 2019-10-13        2242        8       4       2019          10        13
590 2018-08-14        3197       17      27       2018           8        14
473 2019-05-15        1896       25       4       2019           5        15
442 2019-06-04         963       13       1       2019           6         4

In [ ]:
#Month name
date['month_name'] = date['date'].dt.month_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_day,month_name
278,2019-06-08,5024,21,4,2019,6,8,June
317,2018-08-31,3088,14,106,2018,8,31,August
205,2019-12-05,5722,25,260,2019,12,5,December
547,2019-06-21,793,29,3,2019,6,21,June
838,2019-11-23,4191,16,1,2019,11,23,November

In [16]:
#day name

date['day_name'] = date['date'].dt.day_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_day,month_name,day_of_week,day_name
637,2019-02-15,957,22,4,2019,2,15,February,Friday,Friday
631,2019-06-30,4323,4,7,2019,6,30,June,Sunday,Sunday
536,2019-04-24,1140,26,2,2019,4,24,April,Wednesday,Wednesday
623,2018-09-13,4597,3,2,2018,9,13,September,Thursday,Thursday
995,2018-10-08,255,13,1,2018,10,8,October,Monday,Monday

In [17]:
#day of the week
date['day_of_week'] = date['date'].dt.dayofweek
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_day,month_name,day_of_week,day_name
889,2019-07-20,4413,3,7,2019,7,20,July,5,Saturday
492,2019-06-24,2306,14,12,2019,6,24,June,0,Monday
173,2019-01-11,3543,23,1,2019,1,11,January,4,Friday
681,2018-09-08,6483,28,2,2018,9,8,September,5,Saturday
776,2019-08-18,704,13,10,2019,8,18,August,6,Sunday

In [ ]:
#is weekend or not (1: weekend, 0: weekday)
date['is_weekend'] = np.where(date['day_name'].isin(['Saturday']), 1, 0)
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_day,month_name,day_of_week,day_name,is_weekend
12,2019-03-15,5665,5,1,2019,3,15,March,4,Friday,0
244,2019-11-13,2691,25,1,2019,11,13,November,2,Wednesday,0
803,2019-11-09,5296,0,30,2019,11,9,November,5,Saturday,1
89,2019-07-09,7214,22,4,2019,7,9,July,1,Tuesday,0
482,2019-03-29,6791,9,1,2019,3,29,March,4,Friday,0

In [35]:
date['quarter'] = date['date'].dt.quarter
date.sample(5)

,date,date_year,date_month,date_day,month_name,day_of_week,day_name,is_weekend,date_week,quarter
805,2019-11-28,2019,11,28,November,3,Thursday,0,3,4
118,2019-03-12,2019,3,12,March,1,Tuesday,0,1,1
117,2019-05-20,2019,5,20,May,0,Monday,0,0,2
116,2019-04-23,2019,4,23,April,1,Tuesday,0,1,2
903,2019-10-18,2019,10,18,October,4,Friday,0,4,4

In [36]:
date['semester'] = np.where(date['quarter'].isin([1, 2]), 1, 2)
date

,date,date_year,date_month,date_day,month_name,day_of_week,day_name,is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,10,December,1,Tuesday,0,1,4,2
1,2018-08-15,2018,8,15,August,2,Wednesday,0,2,3,2
2,2018-10-23,2018,10,23,October,1,Tuesday,0,1,4,2
3,2019-08-17,2019,8,17,August,5,Saturday,1,5,3,2
4,2019-01-06,2019,1,6,January,6,Sunday,0,6,1,1
...,...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,2018,10,8,October,0,Monday,0,0,4,2
996,2018-12-06,2018,12,6,December,3,Thursday,0,3,4,2
997,2019-05-07,2019,5,7,May,1,Tuesday,0,1,2,1
998,2019-03-03,2019,3,3,March,6,Sunday,0,6,1,1
999,2019-10-15,2019,10,15,October,1,Tuesday,0,1,4,2

In [37]:
import datetime

In [38]:
today = datetime.datetime.today()
today

datetime.datetime(2026, 3, 2, 16, 25, 15, 568691)

In [39]:
today - date['date']

0     2274 days 16:25:15.568691
1     2756 days 16:25:15.568691
2     2687 days 16:25:15.568691
3     2389 days 16:25:15.568691
4     2612 days 16:25:15.568691
                 ...
995   2702 days 16:25:15.568691
996   2643 days 16:25:15.568691
997   2491 days 16:25:15.568691
998   2556 days 16:25:15.568691
999   2330 days 16:25:15.568691
Name: date, Length: 1000, dtype: timedelta64[ns]

In [40]:
(today - date['date']).dt.days

0      2274
1      2756
2      2687
3      2389
4      2612
       ...
995    2702
996    2643
997    2491
998    2556
999    2330
Name: date, Length: 1000, dtype: int64

In [54]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [55]:
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [56]:
time['time'] = time['date'].dt.time
time.sample(5)

,date,msg,time
321,2012-10-09 01:28:00,ИЩУ ДЕВУШКУ БЕЗ КОМПЛЕКСОВ ДЛЯ ВСТРЕЧ 0970028020,01:28:00
675,2014-01-24 22:55:00,щедр красив умен и богат на своем авто! Нуж...,22:55:00
714,2013-07-24 00:03:00,80639357337 ПОЗ С ДОБРОЙ ДЕВУШКОЙ ДЛЯ ДРУЖБЫ смс,00:03:00
442,2014-07-26 00:20:00,есть плохие девочки? 063 410 6482,00:20:00
280,2015-01-02 00:40:00,ХОРОШИЙ ПАРЕНЬ ХОЧЕТ С ДЕВУШКОЙ СЕЙЧАС 095 689...,00:40:00

In [59]:
time['hour'] = time['date'].dt.hour
time['minute'] = time['date'].dt.minute
time['second'] = time['date'].dt.second
time.sample(5)

,date,msg,time,hour,minute,second
347,2012-03-21 01:42:00,Девушки вы где. давайте общаться через чат,01:42:00,1,42,0
593,2015-01-31 00:40:00,п.поцелую девушке0934514694,00:40:00,0,40,0
431,2012-04-06 01:09:00,Пообщаюсь с девушкой от 23 лет 0977768796 ДНЕП...,01:09:00,1,9,0
949,2013-04-17 23:59:00,ищу дев для прият встречь 0632508994,23:59:00,23,59,0
846,2012-09-19 23:58:00,Днепр.м 43 позн.с д/ж для приятных встреч 098....,23:58:00,23,58,0

In [60]:
today - time['date']

0     4460 days 15:35:15.568691
1     4324 days 16:45:15.568691
2     4810 days 16:04:15.568691
3     4112 days 15:54:15.568691
4     4509 days 17:14:15.568691
                 ...
995   5099 days 15:35:15.568691
996   4420 days 17:11:15.568691
997   4885 days 16:48:15.568691
998   5001 days 16:51:15.568691
999   4273 days 17:00:15.568691
Name: date, Length: 1000, dtype: timedelta64[ns]

In [61]:
(today - time['date'])/np.timedelta64(1,'s')

0      3.854001e+08
1      3.736539e+08
2      4.156419e+08
3      3.553341e+08
4      3.896397e+08
           ...
995    4.406097e+08
996    3.819499e+08
997    4.221245e+08
998    4.321471e+08
999    3.692484e+08
Name: date, Length: 1000, dtype: float64

In [62]:

(today - time['date'])/np.timedelta64(1,'m')

0      6.423335e+06
1      6.227565e+06
2      6.927364e+06
3      5.922234e+06
4      6.493994e+06
           ...
995    7.343495e+06
996    6.365831e+06
997    7.035408e+06
998    7.202451e+06
999    6.154140e+06
Name: date, Length: 1000, dtype: float64

In [63]:
(today-time['date']) /np.timedelta64(1,'h')

0      107055.587658
1      103792.754325
2      115456.070991
3       98703.904325
4      108233.237658
           ...
995    122391.587658
996    106097.187658
997    117256.804325
998    120040.854325
999    102569.004325
Name: date, Length: 1000, dtype: float64